services:
  - type: web
    name: CasSet
    env: python
    region: us-central
    buildCommand: |
      echo "Building"
    startCommand: |
      echo "Starting"
    healthCheckPath: /
    plan: free
    autoDeploy: true
